apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: rabbitmq-autoscaling
spec:
  replicas: 1  # Initial replica count; KEDA will manage scaling
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: jyotindersingh/consumer:latest
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
