apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-scaledobject
  namespace: rabbitmq-autoscaling
spec:
  scaleTargetRef:
    name: consumer
  pollingInterval: 5   # Check every 5 seconds
  cooldownPeriod: 30   # Wait 30 seconds before scaling down
  minReplicaCount: 1   # Minimum number of replicas
  maxReplicaCount: 10  # Maximum number of replicas
  triggers:
    - type: rabbitmq
      metadata:
        queueName: task_queue
        mode: QueueLength
        value: "5"
        activationValue: "10"
        host: amqp://guest:guest@rabbitmq:5672/vhost,
        vhostName: /
      authenticationRef:
        name: rabbitmq-trigger-auth
