apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-trigger-auth
  namespace: rabbitmq-autoscaling
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-secret
      key: host
